export type Artist = {
  idArtist: string;
  idLabel?: string;
  intBornYear?: string;
  intDiedYear?: string | null;
  intFormedYear?: string;
  intMembers?: string;
  strArtist: string;
  strArtistAlternate?: string;
  strArtistBanner?: string;
  strArtistClearart?: string;
  strArtistCutout?: string;
  strArtistFanart?: string;
  strArtistFanart2?: string;
  strArtistFanart3?: string;
  strArtistFanart4?: string;
  strArtistLogo?: string;
  strBiographyEN?: string;
  strCountry?: string;
  strCountryCode?: string;
  strDisbanded?: string | null;
  strFacebook?: string;
  strGender?: string;
  strGenre?: string;
  strISNIcode?: string | null;
  strLabel?: string;
  strLastFMChart?: string;
  strLocked?: string;
  strMood?: string;
  strMusicBrainzID?: string;
  strStyle?: string;
  strTwitter?: string;
  strWebsite?: string;
  strArtistThumb?: string;
};
